### ISSUE TITLE
Puzzled by the version number

### ISSUE THREAD

**Issue by orangeclk** [psychobunny/nodebb-plugin-sso-github#6]
I am a developer who want to build a sso plugin for nodebb 0.6.x so I read this repo as an example. However, I find that the version of this plugin in npm is 0.3.1 but in github here is 0.1.3. Thank you!

**Comment by julianlam** [comment]
Hey @orangeclk, please follow my fork instead :smile: 

@psychobunny Can you please disable issues on this repo?

**Comment by julianlam** [comment]
https://github.com/julianlam/nodebb-plugin-sso-github

**Comment by orangeclk** [comment]
@julianlam Thank you!
